# Generated by Django 6.0.6 on 2026-07-07 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('surah_name', models.CharField(max_length=100)),
                ('from_ayah', models.PositiveIntegerField()),
                ('to_ayah', models.PositiveIntegerField()),
                ('quality', models.CharField(choices=[('excellent', 'ممتاز'), ('good', 'جيد'), ('needs_repeat', 'يحتاج تكرار')], max_length=20)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorization_records', to='students.student')),
            ],
            options={
                'verbose_name': 'تسجيل تلاوة',
                'verbose_name_plural': 'سجلات التلاوة',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('read_by_guardian', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملاحظة',
                'verbose_name_plural': 'الملاحظات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('review_type', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري')], max_length=10)),
                ('content', models.CharField(max_length=200)),
                ('quality', models.CharField(choices=[('excellent', 'ممتاز'), ('good', 'جيد'), ('needs_repeat', 'يحتاج تكرار')], max_length=20)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='students.student')),
            ],
            options={
                'verbose_name': 'تسجيل تلاوة',
                'verbose_name_plural': 'سجلات التلاوة',
                'ordering': ['-date'],
            },
        ),
    ]
